"""Strict descriptive peak screen; no unverified narrative attribution."""
def section(data,lang):
    hr=lang=='hr';t=lambda en,cr:cr if hr else en
    fmt=lambda x,d=1:f'{x:.{d}f}'.replace('.',',') if hr else f'{x:.{d}f}'
    cards=[]
    for r in data['extensions']['events']:
        if not r['candidate']:continue
        p=r['period'];m=next(x for x in data['monthly'] if x['period']==p)
        href=('hr.html' if hr else 'index.html')+f'?m_from={p}&m_to={p}&m_metric=rate#vidljivost'
        cards.append(f'''<article id="event-{p}"><h3>{p}</h3><p><strong>{m['hnb_count']}</strong> {t('publications across','objava na')} {r['hnb_domains']} {t('domains','domena')}. {t('Archive rate','Arhivska stopa')}: {fmt(r['rate_per_10000'],2)} / 10.000; {t('screen threshold','prag označavanja')}: {fmt(r['threshold'],2)}.</p><p>{t('Title share','Udio naslova')}: {fmt(100*r['title_share'])}%. {t('Stable-panel / fixed-weight rates','Stope stalnog panela / stalnih pondera')}: {fmt(r['stable_rate_per_10000'],2)} / {fmt(r['fixed_weight_rate'],2)}.</p><a href="{href}">{t('Inspect this month','Pregledaj ovaj mjesec')}</a></article>''')
    return f'''<section class="section" id="vrhovi"><p class="eyebrow">HNB_MEDIA_INDICATORS_1.0</p><h2>{t('Months flagged by the fixed peak rule','Mjeseci označeni stalnim pravilom vrhova')}</h2><p>{t('A month is flagged when its archive rate exceeds the mean of the previous 24 complete months in the same collection regime plus two sample standard deviations. The current month is excluded. Scoring starts in January 2023 and restarts in January 2026 after the collection change.','Mjesec je označen ako njegova arhivska stopa prelazi prosjek prethodna 24 potpuna mjeseca istog režima prikupljanja uvećan za dvije uzoračke standardne devijacije. Tekući mjesec nije uključen. Označavanje počinje u siječnju 2023., a nakon promjene prikupljanja ponovno u siječnju 2026.')}</p><p class="scope-badge">{t('Fixed 2021-01–2026-08 · all eligible sources · descriptive screen; not a significance test. Earlier months with insufficient history are unscored.','Stalno 2021-01–2026-08 · svi prihvatljivi izvori · opisno označavanje; nije test statističke značajnosti. Raniji mjeseci bez dovoljne povijesti nisu ocijenjeni.')}</p><div class="methods-grid">{''.join(cards)}</div><p class="note">{t('These are candidate months, not attributed events. Story-group shares and the contribution of illustrative public articles await corpus matching and independent cluster evaluation.','Ovo su kandidati među mjesecima, a ne pripisani događaji. Udjeli skupina priča i doprinos ilustrativnih javnih članaka čekaju provjeru pripadnosti korpusu i neovisnu procjenu klastera.')}</p><p><a href="data/media/media-event-screen.csv">{t('Every month, score and status · CSV','Svaki mjesec, vrijednost i status · CSV')}</a> · <a href="data/media/media-events.json">JSON</a></p></section>'''
