"""Render the bilingual general hub from approved aggregate inputs."""
from html import escape as e
import json,shutil,os,csv
from media_editorial import briefing, identity, filter_note, explorer_extras, month_inspector, source_tools, source_pager, source_example, method_summary, updates, metadata
from media_chart import chart,number
from media_content import content
from media_extensions_view import FILES as EXTENSION_FILES,latest_panel,panels,context,scope
from report_cards import report_cards
from event_view import section as event_section
from lexical_view import FILES as LEXICAL_FILES, section as lexical_section

def table(headers,rows,body_id=None):
    source=body_id=='media-source-rows'
    if source:
        hr=headers[0]=='Domena izvora'
        headers=['Domena izvora','Objave','Na 10.000','Udio','HNB, filtar','Pozadina, filtar','Rang stope'] if hr else ['Outlet domain','Publications','Per 10,000','Share','HNB, filter','Background, filter','Rate rank']
    head=''.join('<th scope="col" role="columnheader">'+e(x)+'</th>' for x in headers)
    body=''
    for row in rows:
        cells=''
        for i,value in enumerate(row):
            cells+=('<th scope="row" role="rowheader">'+str(value)+'</th>' if i==0 else '<td role="cell" data-label="'+e(headers[i],quote=True)+'">'+str(value)+'</td>')
        body+='<tr role="row">'+cells+'</tr>'
    return '<div class="table-wrap'+(' source-table' if source else '')+'"><table role="table"><thead role="rowgroup"><tr role="row">'+head+'</tr></thead><tbody role="rowgroup"'+(' id="'+body_id+'"' if body_id else '')+'>'+body+'</tbody></table></div>'

def build_media(site,dist):
    data=json.loads((site/'public/data/media/media.json').read_text(encoding='utf-8'));s=data['summary'];release=data['release'];allow=[]
    presentation=json.loads((site/'content/releases.json').read_text(encoding='utf-8'))['presentation_version']
    data['presentation_version']=presentation
    preview='figures/media-social-preview.png'
    (dist/'figures').mkdir(exist_ok=True)
    shutil.copyfile(site/'public'/preview,dist/preview);allow.append(preview)
    for name in ['media.css','media.js','legacy-links.js','lexical.js']:
        shutil.copyfile(site/'src'/name,dist/name);allow.append(name)
    media_files=['media.json','media-monthly.csv','media-source-monthly.csv','media-sources.csv','media-subjects.csv','source-registry.csv','retrieval-audit.csv','retrieval-bridge.csv','platform-audit.csv','subject-definitions.json','releases.json','findings.json','analysis-manifest.json','related-studies.json','report-language.json','report-language.csv']
    media_files+=EXTENSION_FILES+LEXICAL_FILES+['summary.json']
    for p in [site/'public/data/media'/name for name in media_files]:
        name='data/media/'+p.name;(dist/name).parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dist/name);allow.append(name)
    names=['hnb-media-overview-hr.html','hnb-media-overview-hr.pdf','hnb-media-brief-en.html','hnb-media-brief-en.pdf','hnb-media-brief-hr.html','hnb-media-brief-hr.pdf','hnb-media-slides-hr.html','hnb-media-slides-hr.pdf','media-publications.css','media-slides.js','media-citation.txt','media-reuse.txt','media-dictionary.html','media-methods-hr.html','media-methods-en.html','artifacts.json']
    names+=['hnb-reports.css']+[stem+ext for stem in ['hnb-u-medijskom-prostoru','hnb-od-rijeci-do-javnih-pitanja'] for ext in ['.pdf','.html','.webp']]
    names+=['SourceSans3-Regular.woff2','SourceSans3-Semibold.woff2','SourceSerif4Display-Regular.woff2','source-sans-LICENSE.txt','source-serif-LICENSE.txt']
    names+=['PAPER_EXT.pdf','PAPER_EXT.html','PAPER_EXT-citation.txt']
    for name in names:
        p=site/'public/downloads'/name
        if not p.is_file():raise FileNotFoundError(p)
        shutil.copyfile(p,dist/'downloads'/name);allow.append('downloads/'+name)
    artifacts=json.loads((site/'public/downloads/artifacts.json').read_text(encoding='utf-8'))
    for lang,name in [('en','index.html'),('hr','hr.html')]:
        hr=lang=='hr';t=lambda en,hr_:hr_ if hr else en;n=lambda v,d=0:number(v,lang,d);c=content(data,lang)
        sections=[('hnb-pregled',t('Overview','Pregled')),('vidljivost',t('Visibility','Vidljivost')),('teme',t('Subjects','Teme')),('jezik',t('Language','Jezik')),('izvori',t('Sources','Izvori')),('izvjestaj',t('Publications','Publikacije')),('analiza',t('Methods','Metode'))]
        nav=''.join(f'<a href="#{id}">{label}</a>' for id,label in sections)
        facts=''.join(f'<div class="fact"><strong>{a}</strong><span>{b}</span></div>' for a,b in [(n(s['hnb_publications']),t('publications with explicit HNB mentions','objava s izričitim spominjanjem HNB-a')),(n(s['outlets']),t('domains with HNB mentions in the archive','domena sa spominjanjem HNB-a u arhivu')),(n(s['stable_sources']),t('archive sources observed in all 68 full months','arhivskih izvora opaženih u svih 68 punih mjeseci'))])
        findings=''.join(f'<article class="finding" id="{id}"><h3>{e(title)}</h3><p>{e(body)}</p><a href="data/media/findings.json">{t("Evidence record","Zapis o dokazu")} ↗</a></article>' for id,title,body in c['findings'][:3])
        opts=''.join(f'<option value="{r["period"]}">{r["period"]}{" *" if r["coverage_state"]=="partial" else ""}</option>' for r in data['monthly'])
        sourceopts=f'<option value="all">{t("All eligible sources","Svi prihvatljivi izvori")}</option><option value="stable">{t("Observed in every full month","Opaženi u svakom punom mjesecu")}</option>'+''.join(f'<option value="{e(r["source_id"])}">{e(r["source_id"])}</option>' for r in [{'source_id':x} for x in data['selector_sources']])
        controls=f'<div class="controls" hidden data-media-js><label>{t("From","Od")}<select id="media-from">{opts}</select></label><label>{t("Through","Do")}<select id="media-to">{opts}</select></label><label>{t("Source population","Skup izvora")}<select id="media-source">{sourceopts}</select></label><label>{t("Measure","Mjera")}<select id="media-metric"><option value="count">{t("Publication count","Broj objava")}</option><option value="rate">{t("Per 10,000 eligible publications","Na 10.000 prihvatljivih objava")}</option></select></label><button id="media-reset">{t("Reset","Početni prikaz")}</button></div>'
        full=[r for r in data['monthly'] if r['period']<=s['last_full_period']]
        numeric=table([t('Month','Mjesec'),t('HNB count','Broj HNB'),t('HNB passing filter','HNB nakon filtra'),t('All passing filter','Sve nakon filtra'),t('Per 10,000','Na 10.000'),t('Title matches','Podudarni naslovi'),t('Title %','Naslovi %'),t('HNB domains','HNB domene'),t('Background domains','Pozadinske domene'),t('Breadth %','Obuhvat %')],[(r['period'],n(r['hnb_count']),n(r['hnb_i']),n(r['background_i']),n(r['rate_per_10000'],2),n(r['title_mention_count']),n(100*r['title_mention_count']/r['hnb_count'],2),n(r['outlet_breadth']),n(r['active_outlets']),n(100*r['outlet_breadth']/r['active_outlets'],2)) for r in full],'media-numeric-rows')
        subjects=''.join(f'<li><strong>{e(d["label_"+lang])}</strong><span class="amount">{n(s["subject_counts"][d["id"]])} · {n(100*s["subject_counts"][d["id"]]/s["hnb_publications"],1)}%</span> {t("of HNB publications match these words or phrases","objava o HNB-u sadrži ove riječi ili izraze")}</li>' for d in data['subject_definitions'])
        reference_rates={r['source_id']:r for r in data['extensions']['source_rates'] if r['period_id']=='pooled'}
        sources=table([t('Outlet domain','Domena izvora'),t('Publications','Objave'),t('Share of sample','Udio u uzorku')],[(e(r['source_id']),n(r['hnb_count']),n(reference_rates[r['source_id']]['rate_per_10000'],2),n(r['hnb_share']*100,2)+'%',n(reference_rates[r['source_id']]['hnb_i']),n(reference_rates[r['source_id']]['background_i']),n(reference_rates[r['source_id']]['rank']) if reference_rates[r['source_id']]['eligible'] else t('Unranked','Nerangirano')) for r in data['sources']],'media-source-rows')
        sensitivity=table([t('Definition / population','Definicija / skup'),t('Publications, full months','Objave, puni mjeseci')],[(e(k),n(v)) for k,v in c['sensitivity']])
        methods=''.join(f'<article><h3>{e(title)}</h3><p>{e(body)}</p></article>' for title,body in c['methods'])
        audit=list(csv.DictReader((site/'public/data/media/retrieval-audit.csv').open(encoding='utf-8')))
        role_labels={'editorial':('Eligible web publications','Prihvatljive web publikacije'),'hnb_own':('HNB own channels','Vlastiti kanali HNB-a'),'other_own':('Other identified own channels','Ostali prepoznati vlastiti kanali'),'audience':('Audience discussion','Rasprave publike'),'social_unresolved':('Unresolved social accounts','Nerazjašnjeni društveni računi'),'other_media_unresolved':('Other unresolved media','Ostali nerazjašnjeni mediji'),'unknown':('Unclassified web sources','Nerazvrstani web izvori')}
        totals={}
        for r in audit:totals[r['source_role']]=totals.get(r['source_role'],0)+int(r['explicit_publications'])
        audit_table=table([t('Source role','Uloga izvora'),t('Explicit-mention publications','Objave s izričitim spominjanjem')],[(t(*role_labels.get(k,(k,k))),n(v)) for k,v in totals.items()])
        methods+=f'<article><h3>{t("Source-role and text diagnostics","Dijagnostika uloga izvora i teksta")}</h3><p>{t("The table includes all available dates through 10 September 2026, including partial September. Only eligible editorial web publications enter the main series. The other rows describe retrieved candidates, not complete channel inventories.","Tablica obuhvaća sve dostupne datume do 10. rujna 2026., uključujući djelomičan rujan. Samo prihvatljive uredničke web publikacije ulaze u glavnu seriju. Ostali redci opisuju pronađene kandidate, a ne potpune popise kanala.")}</p>{audit_table}<p>{t("Full-month window: ","Razdoblje punih mjeseci: ")}{n(s["with_body"])} {t("publications with non-empty body text; ","objava s nepraznim tekstom; ")}{n(s["exact_body_groups"])} {t("different exact normalized raw-body hashes. These are not unique-story counts; near-copies and boilerplate limit exact matching.","različitih točnih normaliziranih otisaka izvornog teksta. To nije broj jedinstvenih priča; bliske kopije i ponavljajući sadržaj ograničavaju točno podudaranje.")}</p><a href="data/media/retrieval-audit.csv">{t("Retrieval audit · CSV","Provjera pronalaženja · CSV")}</a></article>'
        related=json.loads((site/'public/data/media/related-studies.json').read_text(encoding='utf-8'))
        related_html='<details><summary>'+t('Historical editions and research drafts','Povijesna izdanja i istraživački nacrti')+'</summary>'+''.join('<article><h3>'+e(r['title'])+'</h3><p>'+e('; '.join(r['authors']))+'</p><p>'+e(r['status_'+lang])+' · '+e(r['period'])+' · '+e(r['date_label_'+lang])+'</p><p>'+e(r['compatibility_'+lang])+'</p><p class="source-note">'+e(r['citation'])+'</p></article>' for r in related if r['relation']!='provides_specialist_analysis')+'</details>'
        downloads=[]
        for stem,label in [('hnb-media-overview-hr',t('Substantive overview · Croatian','Cjeloviti pregled · hrvatski')),('hnb-media-brief-'+lang,t('Executive brief · English','Sažetak za odlučivanje · hrvatski')),('hnb-media-slides-hr',t('Findings presentation · Croatian','Prezentacija nalaza · hrvatski'))]:
            a=next(a for a in artifacts if a['file']==stem+'.pdf');downloads.append(f'<li><b>{label}</b><div><a href="downloads/{stem}.html">HTML</a> · <a href="downloads/{stem}.pdf">PDF</a></div><small>{a["pages"]} {t("pages / slides","stranica / slajdova")} · {n(a["bytes"]/1024)} kB · {a["date"]}</small></li>')
        for link,label in [('data/media/media-monthly.csv',t('Monthly aggregates · CSV','Mjesečni agregati · CSV')),('data/media/media-source-monthly.csv',t('Source × month · CSV','Izvor × mjesec · CSV')),('data/media/media-subjects.csv',t('Subject screens · CSV','Tematski skupovi · CSV')),('downloads/media-dictionary.html',t('Data dictionary','Rječnik podataka')),(f'downloads/media-methods-{lang}.html',t('Methods','Metode')),('data/media/source-registry.csv',t('Source registry','Registar izvora')),('downloads/hnb-media-rendering-source.zip',t('Offline rendering source package · ZIP','Izvorni paket za izvanmrežnu izgradnju · ZIP')),('release-manifest.json',t('Release manifest','Manifest izdanja')),('checksums.sha256','SHA-256'),('downloads/artifacts.json',t('Publication metadata','Metapodaci publikacija'))]:downloads.append(f'<li><a href="{link}">{label}</a></li>')
        body=f'''<a class="skip" href="#main">{t('Skip to content','Preskoči na sadržaj')}</a><header><div class="wrap masthead"><a class="wordmark" href="{name}">HNB · {t('Media research','Medijska istraživanja')}</a><a class="language" id="media-language" lang="{'en' if hr else 'hr'}" href="{'index.html' if hr else 'hr.html'}">{'English' if hr else 'Hrvatski'}</a></div></header>
<div class="wrap hero"><p class="eyebrow">{t('Independent research · descriptive release','Neovisno istraživanje · opisno izdanje')}</p><h1>{e(c['title'])}</h1><p class="lead">{t('An independent observatory of HNB mentions in a defined Croatian web-media archive.', 'Neovisni opservatorij spominjanja HNB-a u određenom arhivu hrvatskih internetskih medija.')}</p><p class="edition-line">{t('Edition updated 28 September 2026 · Data through August 2026', 'Izdanje ažurirano 28. rujna 2026. · Podaci do kolovoza 2026.')}</p>{identity(lang)}<div class="actions"><a class="button" href="#vidljivost">{t('Explore the evidence','Istražite podatke')}</a><a class="button secondary" href="downloads/hnb-media-overview-hr.html">{t('Read the overview (Croatian)','Pročitajte cjeloviti pregled')}</a></div>{briefing(data,lang)}</div>
<div class="scope-strip"><div class="wrap"><p>{t('January 2021–August 2026 · Full-month overview · Downloadable data and reports', 'Siječanj 2021. – kolovoz 2026. · Pregled potpunih mjeseci · Podaci i izvještaji za preuzimanje')}</p></div></div><nav class="contents" aria-label="{t('Page contents','Sadržaj stranice')}"><div class="wrap nav-shell"><button id="media-menu" aria-expanded="false" aria-controls="media-nav-links" hidden data-media-js>{t("Sections", "Sadržaj")} <span aria-hidden="true">☰</span></button><div id="media-nav-links">{nav}</div></div></nav>
<main id="main" class="wrap"><section class="section" id="hnb-pregled"><p class="eyebrow">01 · {t('Observed presence','Zabilježena prisutnost')}</p><h2>{t('A broad institutional view, within a defined archive','Širok institucionalni pregled unutar određenog arhiva')}</h2><p class="intro">{t('Explicit mentions across subjects show when and where the institution appears in this monitored web sample. Visibility here is not readership, trust or communication effectiveness.','Izričita spominjanja u različitim temama pokazuju kada se i gdje institucija pojavljuje u ovom praćenom internetskom uzorku. Vidljivost ovdje nije čitanost, povjerenje ni učinkovitost komunikacije.')}</p><div class="facts">{facts}</div><p class="source-note">{t('Headline window: 2021-01–2026-08. Exact register-domain eligibility; repeated captures merged.','Razdoblje glavnih vrijednosti: 2021-01–2026-08. Točno podudaranje domene s upisnikom; ponovljeni zapisi spojeni.')}</p><details class="archive-details"><summary>{t("Archive scope and headline measures", "Obuhvat arhiva i glavne mjere")}</summary><p>{t("These are domains represented in this archive, not a measure of national market coverage.", "Ovo su domene zastupljene u arhivu, a ne mjera obuhvata nacionalnog tržišta.")}</p><div class="finding-list">{findings}</div></details></section>
<section class="section" id="vidljivost"><p class="eyebrow">02 · {t('Time and denominator','Vrijeme i nazivnik')}</p><h2>{t('When do captured HNB mentions appear?','Kada se pojavljuju zabilježena spominjanja HNB-a?')}</h2><p class="intro">{t('Compare publication counts with the rate per 10,000 eligible archive publications. Choose a shorter period or inspect individual months below.', 'Usporedite broj objava sa stopom na 10.000 prihvatljivih arhivskih objava. Odaberite kraće razdoblje ili pregledajte pojedinačne mjesece ispod grafikona.')}</p>{filter_note(lang)}{explorer_extras(lang)}{controls}<p class="view-status" id="media-view-status">2021-01–2026-08 · {n(s['hnb_publications'])} {t('observed publications','opaženih objava')}</p><p id="media-empty" class="empty-state" hidden></p><figure class="figure"><h3 id="media-chart-label">{t('Publications containing explicit HNB mentions','Objave s izričitim spominjanjem HNB-a')}</h3><div id="media-chart">{chart(full,lang,show_boundary=False)}</div><figcaption id="media-selected-note">{t('Counts and rates describe the monitored archive. See the technical definitions for capture and date coverage.', 'Brojevi i stope opisuju praćeni arhiv. Tehničke definicije opisuju prikupljanje i zastupljenost datuma.')}</figcaption></figure>{month_inspector(lang)}<div class="actions" hidden data-media-js><button id="media-export-csv">CSV</button><button id="media-export-svg">SVG</button><button id="media-copy">{t('Copy view link','Kopiraj poveznicu prikaza')}</button><button id="media-definition-open">{t('Definitions','Definicije')}</button></div><label class="sr-only" for="media-copy-fallback">{t('Link to copy','Poveznica za kopiranje')}</label><input id="media-copy-fallback" hidden readonly><details><summary>{t('Numeric alternative and matched denominators','Brojčani prikaz i usklađeni nazivnici')}</summary>{numeric}<p class="source-note">{t('A dash means unavailable, not zero. An asterisk marks a partial month.','Crtica označava nedostupnu vrijednost, a ne nulu. Zvjezdica označava djelomičan mjesec.')}</p></details><noscript><p class="note">{t('The complete default chart and table are available without JavaScript. Use aggregate downloads for other views.','Cijeli početni grafikon i tablica dostupni su bez JavaScripta. Za druge prikaze koristite preuzimanje agregata.')}</p></noscript></section>
<section class="section" id="teme"><p class="eyebrow">03 · {t('Exploratory subject screens','Istraživački pregled tema')}</p><h2>{t('Which subjects are present in the captured text?','Koje su teme prisutne u zabilježenom tekstu?')}</h2><p class="intro">{t('Eight overlapping keyword screens show which words accompany HNB mentions. Each percentage uses all 33,235 HNB publications as its denominator. An article can match several screens, so the shares do not add to 100%.', 'Osam preklapajućih skupova ključnih riječi pokazuje koje riječi prate spominjanje HNB-a. Nazivnik svakog postotka čine sve 33.235 objave o HNB-u. Jedna objava može odgovarati više skupova, pa se udjeli ne zbrajaju u 100%.')}</p><ul class="subject-list">{subjects}</ul><p class="note">{e(c['sections'][4][1][2])}</p><p class="source-note">2021-01–2026-08 · {t('Title and body; overlapping keyword matches, not main-topic assignments.','Naslov i tekst; preklapajuća podudaranja ključnih riječi, a ne oznake glavne teme.')} <a href="data/media/subject-definitions.json">{t('Exact definitions','Točne definicije')}</a></p></section>
<section class="section" id="izvori"><p class="eyebrow">04 · {t('Source composition','Sastav izvora')}</p><h2>{t('Where does the observed coverage appear?','Gdje se pojavljuju opažene objave?')}</h2><p class="intro">{e(c['findings'][1][2])}</p><p>{t('Count shows how many captured publications mention HNB. Rate shows how often HNB appears relative to an outlet’s eligible archive output: the outlet with the most articles need not have the highest rate.', 'Broj pokazuje koliko zabilježenih objava spominje HNB. Stopa pokazuje koliko se često HNB pojavljuje u prihvatljivim arhivskim objavama izvora: izvor s najviše članaka ne mora imati najvišu stopu.')}</p>{source_example(data,lang)}{source_tools(lang)}<label hidden data-media-js>{t('Order sources','Poredaj izvore')} <select id="media-sort"><option value="count">{t('By count','Prema broju')}</option><option value="name">{t('Alphabetically','Abecedno')}</option></select></label><p id="media-source-scope" class="source-note">2021-01–2026-08 · {t('all archive domains; includes sources with no HNB mentions','sve arhivske domene; uključeni su izvori bez spominjanja HNB-a')}</p>{source_pager(lang)}{sources}<p class="source-note">{t('The table follows the selected dates and compares all eligible sources. It does not inherit the chart’s single-source selection.','Tablica prati odabrane datume i uspoređuje sve prihvatljive izvore. Ne preuzima odabir pojedinačnog izvora iz grafikona.')} <a href="data/media/media-sources.csv">{t('Complete ranking · CSV','Cijeli poredak · CSV')}</a></p><details><summary>{t('Sensitivity to retrieval and source scope','Osjetljivost na pronalaženje i skup izvora')}</summary>{sensitivity}<p>{e(c['sections'][5][1][1])}</p></details></section>
<div id="istrazivanja" class="library-group"><h3>{t('Specialist study','Specijalistička studija')}</h3><article class="study-card"><p class="eyebrow">{t('Specialist study · separate corpus','Specijalistička studija · zaseban korpus')}</p><h3>{t('HNB in the inflation debate','HNB u raspravi o inflaciji')}</h3><p>{e(c['sections'][6][1][0].replace('; author review pending','').replace('; autorska provjera u tijeku',''))}</p><p class="source-note">Petra Palić · Luka Sikić · 28. 9. 2026.<br><i>Pasivno zamijenjena: cijena inflacije koju ne mjeri indeks potrošačkih cijena</i><br>{t('18 pages · Croatian manuscript','18 stranica · hrvatski rukopis')}</p><div class="actions"><a class="button" href="downloads/PAPER_EXT.pdf" download lang="hr">{t('Download paper · PDF','Preuzmi rad · PDF')}</a><a class="button" href="downloads/PAPER_EXT.html" download lang="hr">{t('Download paper · HTML','Preuzmi rad · HTML')}</a></div><p><a href="downloads/PAPER_EXT.html" lang="hr">{t('Read the paper online','Pročitaj rad na stranici')}</a> · <a href="downloads/PAPER_EXT-citation.txt" download>{t('Citation','Citat')}</a></p></article><p class="note">{e(c['sections'][6][1][1])}</p></div><div class="library-group"><h3>{t('Earlier reading editions','Ranija izdanja za čitanje')}</h3><p>{t('Earlier overview, brief and slides are retained for reference. Start with the two current reports above.', 'Raniji pregled, sažetak i slajdovi zadržani su kao referentni materijali. Započnite s dva aktualna izvještaja iznad.')}</p><details><summary>{t('Earlier overview, brief and slides','Raniji pregled, sažetak i slajdovi')}</summary><ul class="download-list">{''.join(downloads[:3])}</ul></details>{related_html}</div><p><a href="#analiza">{t('Data and methods →','Podaci i metode →')}</a></p></section>
<section class="section" id="analiza"><p class="eyebrow">06 · {t('Methods and release','Metode i izdanje')}</p><h2>{t('Read the limits alongside the numbers','Čitajte ograničenja uz brojke')}</h2>{method_summary(lang)}<p><a class="button secondary" href="methods-{lang}.html">{t("Full methods and data guide", "Cjelovite metode i vodič kroz podatke")} →</a></p><p class="source-note">{t('Eligibility reference','Izvor za prihvatljivost')}: <a href="https://aem.hr/elektronicke-publikacije/">{t('Agency for Electronic Media register','Upisnik Agencije za elektroničke medije')}</a> · 21. 9. 2026. · <a href="data/media/analysis-manifest.json">{t('Analysis lineage','Analitičko podrijetlo')}</a></p><details><summary>{t('Download data and reproducible inputs','Preuzmite podatke i ulazne datoteke za ponovljivost')}</summary><ul class="download-list">{''.join(downloads[3:])}</ul></details><p>{t('The public source package rebuilds the website from published aggregates and prepared assets. Recreating article-level aggregates requires access to the restricted archive and analysis pipeline; article text is not distributed.', 'Javni paket izvornog koda ponovno gradi stranicu iz objavljenih agregata i pripremljenih datoteka. Za ponovnu izradu agregata na razini objava potreban je pristup ograničenom arhivu i analitičkom postupku; tekstovi članaka ne distribuiraju se.')}</p><p><a href="downloads/media-citation.txt">{t('Citation','Citiranje')}</a> · <a href="downloads/media-reuse.txt">{t('Reuse and data restrictions','Ponovna uporaba i ograničenja podataka')}</a></p>{updates(lang,presentation)}</section></main>
<footer class="footer"><div class="wrap">{t('Independent research resource; no HNB affiliation or endorsement is implied.','Neovisni istraživački izvor; ne podrazumijeva pripadnost HNB-u ni njegovo odobrenje.')}<br>HNB_MEDIA · {t('data','podaci')} {release['data_version']} · {t('method','metoda')} {release['method_version']} · {t('presentation','prikaz')} {presentation}</div></footer>
<dialog id="media-definition" aria-labelledby="media-definition-title"><h2 id="media-definition-title">{t('Count, rate and coverage','Broj, stopa i obuhvat')}</h2><p>{e(c['methods'][3][1])}</p><p>{e(c['methods'][4][1])}</p><button id="media-definition-close">{t('Close','Zatvori')}</button></dialog><p class="sr-only" id="media-announcement" aria-live="polite"></p><script id="media-data" type="application/json">{json.dumps(data,ensure_ascii=False,separators=(',',':'),allow_nan=False).replace('<',chr(92)+'u003c')}</script><script src="media.js" defer></script>'''
        body=body.replace('<div id="istrazivanja"',event_section(data,lang)+report_cards(artifacts,lang).removesuffix('</section>')+'<div id="istrazivanja"')
        body=body.replace('<details class="archive-details">',latest_panel(data,lang,table)+'<details class="archive-details">')
        body=body.replace('<div class="controls"','<p id="media-state-warning" class="note" role="status" hidden></p><div class="controls"',1)
        body=body.replace('<section class="section" id="teme">',panels(data,lang,table)+'<section class="section" id="teme"><span id="V4"></span>')

        body=body.replace('<option value="rate">'+t('Per 10,000 eligible publications','Na 10.000 prihvatljivih objava')+'</option>', '<option value="rate">'+t('Per 10,000 eligible publications','Na 10.000 prihvatljivih objava')+'</option><option value="title">'+t('Title matches (%)','Podudaranja u naslovu (%)')+'</option><option value="breadth">'+t('Outlet breadth (%)','Obuhvat izvora (%)')+'</option>')
        body=body.replace('<option value="name">'+t('Alphabetically','Abecedno')+'</option>', '<option value="name">'+t('Alphabetically','Abecedno')+'</option><option value="rate">'+t('By eligible archive rate','Prema prihvatljivoj arhivskoj stopi')+'</option>')
        body=body.replace('</label><p id="media-source-scope"','</label><div class="actions" hidden data-media-js><button data-source-window="pooled">2021–2026</button><button data-source-window="legacy">2021–2023</button><button data-source-window="api">2024–2026</button><button id="media-export-sources">'+t('All domains in selected dates · CSV','Sve domene u odabranom razdoblju · CSV')+'</button></div><p class="note">'+t('Rate ranking: at least 5,000 matching-filter background publications AND 50 matching-filter HNB publications in the selected window. Below-threshold sources are unranked. Counts remain available for every source.','Poredak stopa: najmanje 5.000 pozadinskih objava s istim filtrom I 50 objava o HNB-u s istim filtrom u odabranom razdoblju. Izvori ispod praga nisu rangirani. Brojevi ostaju dostupni za sve izvore.')+'</p><p id="media-source-scope"')
        body=body.replace('<p class="view-status" id="media-view-status"',scope(data,lang,t('publications / domains','objave / domene'),t('matching-filter archive / HNB publications / background domains','arhiv s istim filtrom / objave o HNB-u / pozadinske domene'))+'<p class="view-status" id="media-view-status"')
        # Source headers and mobile labels are rendered together in table().
        body=body.replace('data/media/media-sources.csv">'+t('Complete ranking · CSV','Cijeli poredak · CSV'), 'data/media/media-source-rates.csv">'+t('All three reference windows · CSV','Sva tri referentna razdoblja · CSV'))
        body=body.replace('<div class="figure" id="composition-chart"></div>', '<div class="figure" id="composition-chart"><p>'+t('The numeric comparison below is available without JavaScript.','Brojčana usporedba u nastavku dostupna je bez JavaScripta.')+'</p></div>')
        body=body.replace('<ul class="subject-list">',scope(data,lang,t('publications; fixed 2021-01–2026-08; all eligible sources','objave; stalno 2021-01–2026-08; svi prihvatljivi izvori'),t('all HNB publications; overlapping screens','sve objave o HNB-u; preklapajući skupovi'),True)+'<ul class="subject-list">')
        body=body.replace('<p id="media-source-scope"',scope(data,lang,t('domains; selected dates; all eligible sources','domene; odabrani datumi; svi prihvatljivi izvori'),t('matching-filter archive publications','arhivske objave s istim filtrom'))+'<p id="media-source-scope"')

        body=body.replace('href="downloads/hnb-media-overview-hr.html">'+t('Read the overview (Croatian)','Pročitajte cjeloviti pregled'), 'href="#izvjestaj">'+t('Read the two reports (Croatian)','Pročitajte dva izvještaja'),1)
        lexical=json.loads((site/'public/data/media/lexical-extensions.json').read_text(encoding='utf-8'))
        body=body.replace('<section class="section" id="izvori">',lexical_section(lexical,lang,table)+'<section class="section" id="izvori">')
        template=(site/'src'/name).read_text(encoding='utf-8')
        for k,v in {'LANG':lang,'TITLE':e(c['title']),'DESCRIPTION':e(c['lead']),'BODY':body}.items():template=template.replace('@@'+k+'@@',v)
        base=(os.environ.get('SITE_URL') or json.loads((site/'content/releases.json').read_text(encoding='utf-8'))['canonical_url'] or '').rstrip('/')
        description=t('Independent observatory of HNB mentions in Croatian web media. Latest reading, source comparisons, reports and downloadable data. Updated 28 September 2026.', 'Neovisni opservatorij spominjanja HNB-a u hrvatskim internetskim medijima. Najnoviji pregled, usporedbe izvora, izvještaji i podaci. Ažurirano 28. rujna 2026.')
        template=template.replace(e(c['lead']),e(description))
        template=template.replace('</head>',metadata(base,name,c['title'],description,lang,presentation)+'</head>')
        guide_title=t('Methods and data guide', 'Metode i vodič kroz podatke')
        guide=f'<a class="skip" href="#main">{t("Skip to content","Preskoči na sadržaj")}</a><header><div class="wrap masthead"><a href="{name}#analiza">← {t("Back to the observatory","Povratak na opservatorij")}</a><a href="methods-{"en" if hr else "hr"}.html">{"English" if hr else "Hrvatski"}</a></div></header><main id="main" class="wrap"><section class="section"><h1>{guide_title}</h1>{method_summary(lang)}<details><summary>{t("Full technical definitions and archive diagnostics","Cjelovite tehničke definicije i dijagnostika arhiva")}</summary><div class="methods-grid">{methods}</div></details><h2>{t("Protocol and files","Protokol i datoteke")}</h2><ul class="download-list">{"".join(downloads[3:])}</ul><details><summary>{t("External survey context","Vanjski anketni kontekst")}</summary>{context(lang)}</details></section></main>'
        guide_template=(site/'src'/name).read_text(encoding='utf-8')
        for key,value in {'LANG':lang,'TITLE':guide_title,'DESCRIPTION':guide_title,'BODY':guide}.items():guide_template=guide_template.replace('@@'+key+'@@',value)
        guide_name=f'methods-{lang}.html'
        guide_template=guide_template.replace('</head>',f'<link rel="canonical" href="{e(base)}/{guide_name}"></head>')
        (dist/guide_name).write_text(guide_template,encoding='utf-8');allow.append(guide_name)
        assert '@@' not in template
        (dist/name).write_text(template,encoding='utf-8');allow.append(name)
    return allow
