"""Shared bilingual narrative: pages, reports, briefs and deck use one evidence contract."""
from media_chart import number
from media_extensions_view import narratives

def content(data,lang='hr'):
    hr=lang=='hr';t=lambda en,hr_:hr_ if hr else en;n=lambda v,d=0:number(v,lang,d);s=data['summary'];total=s['hnb_publications'];percent=lambda v:n(v/total*100,1)+'%'
    title=t('The Croatian National Bank in Croatian media','Hrvatska narodna banka u hrvatskim medijima')
    lead=t('When does HNB appear in the monitored media, in which outlets, and alongside which subjects? A descriptive view of captured web publications, with a separate study of the inflation debate.','Kada se HNB pojavljuje u praćenim medijima, u kojim izvorima i uz koje teme? Opisni pregled zabilježenih internetskih objava, s odvojenom studijom rasprave o inflaciji.')
    scope=t('January 2021–August 2026 · September available through 10 September · research release candidate, author review pending.','Siječanj 2021. – kolovoz 2026. · rujan dostupan do 10. rujna · istraživački prijedlog izdanja, autorska provjera u tijeku.')
    findings=[
      ('V1',t(f'{n(total)} publications mention HNB explicitly',f'{n(total)} objava izričito spominje HNB'),t(f'The captured sample includes {n(s["outlets"])} registered outlets. Each source–publication identity counts once; repeated captures are merged. This measures observed publication presence, not audience exposure.',f'Broj zastupljenih registriranih izvora u uzorku iznosi {n(s["outlets"])}. Svaka kombinacija izvora i identiteta objave broji se jednom; ponovljeni zapisi spajaju se. Mjeri se prisutnost u objavama, a ne izloženost publike.')),
      ('V2',t(f'Five outlets account for {n(s["top_five_share"]*100,1)}% of the sample',f'Pet izvora čini {n(s["top_five_share"]*100,1)}% uzorka'),t('The largest contributors are ranked by publication count within the same full-month window. This is concentration across outlet domains; ownership and readership are not measured.','Najzastupljeniji izvori rangirani su prema broju objava u istom razdoblju punih mjeseci. Riječ je o koncentraciji prema domenama izvora; vlasništvo i čitanost nisu izmjereni.')),
      ('V3',t(f'{percent(s["title_mentions"])} also name HNB in the title',f'{percent(s["title_mentions"])} spominje HNB i u naslovu'),t(f'{n(s["title_mentions"])} retained titles contain the acronym or formal name. A title match is a narrow observable marker. It does not establish the bank’s main role, quotation, stance or substantive prominence.',f'{n(s["title_mentions"])} zadržana naslova sadrže kraticu ili službeni naziv. Podudaranje u naslovu usko je opažljivo obilježje. Ono ne utvrđuje glavnu ulogu banke, citiranje, stav ni sadržajnu istaknutost.')),
      ('V4',t('Coverage extends across several institutional subjects','Objave obuhvaćaju više institucionalnih tema'),t('The development audit found coverage of loans, cash and euro conversion, bank supervision, statistics and governance. Eight overlapping keyword screens support exploration; they are not validated topic-prevalence estimates.','Razvojni pregled pronašao je objave o kreditima, gotovini i konverziji u euro, nadzoru banaka, statistici i upravljanju. Osam preklapajućih skupova ključnih riječi služi istraživanju građe; oni nisu validirane procjene učestalosti tema.'))
    ]
    methods=[
      (t('What is included?','Što je uključeno?'),t('Web records whose source domain exactly matches the current Agency for Electronic Media register are eligible. A domain is used as the outlet identity. Official HNB and identified institutional or association channels are separated; social media and audience discussion are outside the main series. Current registration does not prove historical registration or Croatian-language content. Ownership and complete outlet capture remain unknown.','Prihvatljivi su internetski zapisi čija se domena izvora točno podudara s aktualnim upisnikom Agencije za elektroničke medije. Domena označava identitet izvora. Službeni kanali HNB-a i prepoznati institucionalni ili udrugovni kanali odvojeni su; društvene mreže i rasprave publike izvan su glavne serije. Aktualni upis ne dokazuje povijesni status ni hrvatski jezik sadržaja. Vlasništvo i potpunost obuhvata izvora ostaju nepoznati.')),
      (t('What is an HNB mention?','Što je spominjanje HNB-a?'),t('The retained title or body must contain the bounded acronym HNB (including Croatian case suffixes) or a form of Hrvatska narodna banka / Croatian National Bank. Generic central-bank phrases, officeholder surnames and snippet-only matches are separate candidate diagnostics. Mentions may be incidental, historical or critical. They are not assertions that an action attributed to HNB really occurred.','Zadržani naslov ili tekst mora sadržavati omeđenu kraticu HNB (uključujući padežne nastavke) ili oblik naziva Hrvatska narodna banka / Croatian National Bank. Opći izrazi za središnju banku, prezimena dužnosnika i podudaranja samo u sažetku zasebni su dijagnostički skupovi kandidata. Spominjanja mogu biti usputna, povijesna ili kritička. Ona ne potvrđuju da se radnja pripisana HNB-u doista dogodila.')),
      (t('How are publications counted?','Kako se broje objave?'),t('Repeated captures on the same outlet and normalized article URL are merged. If an article URL is unavailable, the fallback uses source, record date and normalized title. The longest captured body is retained and mentions are checked again. First record date sets the month. URL updates can be merged; URL variants can survive. Cross-outlet copies count separately because outlet publication is the unit. Exact text hashes are a limited diagnostic, not a count of unique stories.','Ponovljeni zapisi istog izvora i normalizirane adrese članka spajaju se. Ako adresa članka nije dostupna, zamjenski ključ čine izvor, datum zapisa i normalizirani naslov. Zadržava se najdulji tekst i ponovno provjerava spominjanje. Mjesec određuje prvi datum zapisa. Ažuriranja iste adrese mogu se spojiti, a inačice adresa ostati odvojene. Preneseni tekstovi u različitim izvorima broje se zasebno jer je jedinica objava u izvoru. Točni otisci teksta ograničena su dijagnostika, a ne broj jedinstvenih priča.')),
      (t('What does the rate divide by?','Koji je nazivnik stope?'),t('The rate is 10,000 times HNB-mention publications passing the archive’s standalone-i query divided by all publications passing that same query in the same eligible domains and months. Both sides use the same publication identity. From January 2024 the API batch was collected with this filter; the legacy batch is filtered locally to match. The unknown original legacy selection and changing vendor capture still prevent a national market-share interpretation.','Stopa je 10.000 puta broj objava sa spominjanjem HNB-a koje prolaze arhivski upit za samostalno slovo i, podijeljen svim objavama koje prolaze isti upit u istim prihvatljivim domenama i mjesecima. Obje strane koriste isti identitet objave. Od siječnja 2024. API skup prikuplja se s tim filtrom; na stariji skup filtar se primjenjuje lokalno. Nepoznata početna selekcija starijeg skupa i promjenjivi obuhvat dobavljača i dalje onemogućuju tumačenje kao nacionalnog medijskog udjela.')),
      (t('Where are the boundaries?','Gdje su granice usporedbe?'),t('The current archive contains records for every calendar day from January 2021 to 10 September 2026. This establishes date coverage, not complete article capture. Its collection regime changes in January 2024. The repaired first quarter of 2024 is available here, while the frozen inflation study retains its missing media period and April 2024 boundary. September is partial and excluded from headline totals.','Aktualni arhiv ima zapise za svaki kalendarski dan od siječnja 2021. do 10. rujna 2026. Time se utvrđuje zastupljenost datuma, a ne potpunost prikupljenih članaka. Način prikupljanja mijenja se u siječnju 2024. Obnovljeno prvo tromjesečje 2024. dostupno je u ovom pregledu, dok zamrznuta studija inflacije zadržava nedostupne medijske mjesece i granicu u travnju 2024. Rujan je djelomičan i isključen iz glavnih ukupnih vrijednosti.')),
      (t('What was reviewed?','Što je provjereno?'),t('A deterministic development sample covered retrieval routes and both collection regimes, supplemented by source-stratified explicit hits, exact-text groups and 32 background non-hits. The audit removed a currency-converter footer and identified related-content links. Remaining page navigation can still create matches. This was an agent-led development audit. There is no independent human validation, precision/recall estimate or validated subject classification.','Deterministički razvojni uzorak obuhvatio je putove pronalaženja i oba načina prikupljanja, uz dodatni pregled izričitih podudaranja po izvorima, skupina istovjetnog teksta i 32 pozadinska zapisa bez podudaranja. Uklonjeno je podnožje pretvornika valuta te su prepoznate poveznice na povezani sadržaj. Preostala navigacija stranice još može stvarati podudaranja. Pregled je proveo agent tijekom razvoja. Nema neovisne ljudske validacije, procjene preciznosti i odziva ni validirane klasifikacije tema.'))
    ]
    sensitivity=[
      (t('Primary exact-mention definition','Primarna definicija izričitog spominjanja'),total),
      (t('Formal name only','Samo službeni naziv'),s['formal_mentions']),
      (t('Title mentions only','Samo spominjanja u naslovu'),s['title_mentions']),
      (t('Non-empty captured body','S nepraznim zabilježenim tekstom'),s['with_body']),
      (t(f'{s["stable_sources"]} sources observed in all full months',f'{s["stable_sources"]} izvora opaženih u svim punim mjesecima'),s['stable_hnb']),
      (t('Excluding two sources with detected related links','Bez dvaju izvora s otkrivenim povezanim sadržajem'),s['excluding_two_related_content_sources'])
    ]
    sections=[
      (t('Reading this release','Kako čitati ovo izdanje'),[lead,scope,t('Visibility here means a captured publication containing an explicit institutional reference. It does not measure how many people saw the item, understood it or trusted the bank. A broad institutional question requires a broad article population; no inflation keyword is required for entry.','Vidljivost ovdje znači zabilježenu objavu koja sadrži izričitu referencu na instituciju. Ne mjeri koliko je ljudi vidjelo objavu, razumjelo je ili vjerovalo banci. Široko institucionalno pitanje zahtijeva širok skup objava; za ulazak nije potrebna ključna riječ povezana s inflacijom.')]),
      (t('Corpus and source selection','Korpus i odabir izvora'),[methods[0][1],methods[1][1],methods[2][1]]),
      (t('Time, counts and denominators','Vrijeme, brojevi i nazivnici'),[methods[4][1],methods[3][1],t('Compare months within a collection regime and inspect the observed-source panel. Even sources present in all 68 full months may have changing capture intensity. Neither a rising count nor a falling rate alone establishes a change in national public attention. The monthly table and exports retain the numerator, denominator and coverage state.','Uspoređujte mjesece unutar istog načina prikupljanja i pregledajte skup stalno opaženih izvora. Čak i izvori prisutni u svih 68 punih mjeseci mogu imati promjenjiv intenzitet prikupljanja. Ni rast broja ni pad stope samostalno ne utvrđuju promjenu nacionalne javne pozornosti. Mjesečna tablica i izvozi čuvaju brojnik, nazivnik i stanje obuhvata.')]),
      (t('Where the captured coverage appears','Gdje se pojavljuju zabilježene objave'),[findings[1][2],t('Source counts describe the archive after eligibility and retrieval decisions. Sources absent from the current register, unmatched aliases, print and broadcast records, and unresolved social accounts are excluded from the primary web population. Exclusion does not mean those sources never cover HNB. Outlet rankings should not be interpreted as editorial quality or communication effectiveness.','Brojevi po izvorima opisuju arhiv nakon odluka o prihvatljivosti i pronalaženju. Izvori izvan aktualnog upisnika, nepovezani nazivi domena, tisak i emitirani sadržaji te nerazjašnjeni računi društvenih mreža isključeni su iz primarnog internetskog skupa. Isključenje ne znači da ti izvori ne izvještavaju o HNB-u. Poredak izvora ne treba tumačiti kao novinarsku kvalitetu ili učinkovitost komunikacije.')]),
      (t('Subjects and observable title mentions','Teme i opažljiva spominjanja u naslovu'),[findings[3][2],findings[2][2],t(f'The screens overlap: {n(s["multiple_tags"])} publications match more than one; {n(s["untagged"])} match none. They search retained title and body for predefined stems and phrases. A match anywhere in a page does not assign its main topic or the HNB-relevant passage. Empty body text also limits assessment; {n(total-s["with_body"])} included publications rely on their titles. Non-empty text is not proof of complete text.',f'Skupovi ključnih riječi preklapaju se: {n(s["multiple_tags"])} objava odgovara više skupova, a {n(s["untagged"])} nijednom. U zadržanom naslovu i tekstu traže se unaprijed određene osnove riječi i izrazi. Podudaranje bilo gdje na stranici ne određuje glavnu temu ni dio teksta povezan s HNB-om. Prazan tekst dodatno ograničava procjenu; {n(total-s["with_body"])} uključenih objava oslanja se na naslov. Neprazan tekst ne dokazuje cjelovitost.')]),
      (t('Sensitivity and development review','Osjetljivost i razvojna provjera'),[methods[5][1],t('The alternative totals change the definition or source population; they are not confidence intervals. Formal-name-only retrieval misses acronym-only publications. Restriction to sources observed every month reduces composition changes but cannot repair unknown collection intensity. The two-source exclusion removes Dnevnik.hr and Vecernji.hr, where related links were detected, as a deliberately broad contamination check.','Alternativni ukupni brojevi mijenjaju definiciju ili skup izvora; oni nisu intervali pouzdanosti. Pretraživanje samo službenog naziva propušta objave koje koriste samo kraticu. Ograničenje na izvore opažene svakog mjeseca smanjuje promjene sastava, ali ne uklanja nepoznati intenzitet prikupljanja. Izostavljanje Dnevnik.hr i Vecernji.hr, gdje su otkrivene povezane poveznice, namjerno je široka provjera mogućeg onečišćenja sadržaja.')]),
      (t('A separate question: the inflation debate','Odvojeno pitanje: rasprava o inflaciji'),[t('The extended inflation study by Petra Palić and Luka Sikić (17 September 2026; author review pending) examines weighted institutional visibility inside an inflation corpus through May 2026. Its primary weekly association is a 0.21 percentage-point lower weighted share per one percentage-point higher inflation; time controls qualify that association. A stable link to consumer expectations is not established. Those models and their saved inputs have not been rerun for this release.','Proširena studija Petre Palić i Luke Sikića (17. rujna 2026.; autorska provjera u tijeku) proučava ponderiranu institucionalnu vidljivost unutar inflacijskog korpusa do svibnja 2026. Primarna tjedna povezanost iznosi 0,21 postotni bod nižeg ponderiranog udjela uz inflaciju višu za jedan postotni bod; vremenske kontrole ograničavaju taj zaključak. Stabilna veza s očekivanjima potrošača nije utvrđena. Ti modeli i njihovi spremljeni ulazni podaci nisu ponovno procijenjeni za ovo izdanje.'),t('Its weighted inflation denominator and broad-media publication counts are different estimands. Current first-quarter 2024 repairs cannot be inserted into frozen regressions without a new analytical edition. Generic central-bank candidates in the older retrieval also cannot be relabeled as confirmed HNB coverage.','Ponderirani inflacijski nazivnik i broj objava u širokom medijskom pregledu različite su veličine. Aktualna obnova prvog tromjesečja 2024. ne može se umetnuti u zamrznute regresije bez novog analitičkog izdanja. Opći kandidati za središnje banke iz starijeg pretraživanja također se ne mogu preimenovati u potvrđene objave o HNB-u.')]),
      (t('Research priorities and reproducibility','Istraživački prioriteti i ponovljivost'),[t('The next measurement priority is independent entity-attribution and non-hit assessment, followed by separately coded prominence, role, quotation and subject labels. Trust requires an appropriate survey; official-message uptake requires an inventory and validated matching. None is inferred from a mention count.','Sljedeći je mjerni prioritet neovisna provjera pripisivanja instituciji i zapisa bez podudaranja, zatim zasebno kodiranje istaknutosti, uloge, citiranja i tema. Za povjerenje je potrebna odgovarajuća anketa; za preuzimanje službenih poruka popis službenih objava i validirano povezivanje. Ništa od toga ne izvodi se iz broja spominjanja.'),t('The public source package rebuilds the static site offline from approved aggregates and publication assets. Regenerating article-level aggregates requires authorized access to the restricted archive and the private pipeline. Vendor article text and identifiers are not distributed. The public research draft is available at lusiki.github.io/HNB_Media_Attention/media/. No DOI is assigned; author review remains pending.','Javni paket izvornog koda ponovno gradi statičku stranicu iz odobrenih agregata i publikacijskih datoteka, bez pristupa mreži. Ponovna izrada agregata na razini objava zahtijeva ovlašten pristup ograničenom arhivu i privatnom postupku obrade. Tekstovi članaka i identifikatori dobavljača ne distribuiraju se. Javni istraživački nacrt dostupan je na lusiki.github.io/HNB_Media_Attention/media/. DOI nije dodijeljen; autorska provjera još je u tijeku.')])
    ]
    return {'title':title,'lead':lead,'scope':scope,'findings':findings,'methods':methods,'sensitivity':sensitivity,'sections':sections,'extension_findings':narratives(data,lang)}
