"""Render the bilingual general hub from approved aggregate inputs."""
from html import escape as e
import json,shutil,os,csv
from media_chart import chart,number
from media_content import content
from report_cards import report_cards

def table(headers,rows,body_id=None):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+e(x)+'</th>' for x in headers)+'</tr></thead><tbody'+(' id="'+body_id+'"' if body_id else '')+'>'+''.join('<tr>'+''.join(('<th scope="row">' if i==0 else '<td>')+str(v)+('</th>' if i==0 else '</td>') for i,v in enumerate(r))+'</tr>' for r in rows)+'</tbody></table></div>'

def build_media(site,dist):
    data=json.loads((site/'public/data/media/media.json').read_text(encoding='utf-8'));s=data['summary'];release=data['release'];allow=[]
    for name in ['media.css','media.js','legacy-links.js']:
        shutil.copyfile(site/'src'/name,dist/name);allow.append(name)
    media_files=['media.json','media-monthly.csv','media-source-monthly.csv','media-sources.csv','media-subjects.csv','source-registry.csv','retrieval-audit.csv','retrieval-bridge.csv','platform-audit.csv','subject-definitions.json','releases.json','findings.json','analysis-manifest.json','related-studies.json','report-language.json','report-language.csv']
    for p in [site/'public/data/media'/name for name in media_files]:
        name='data/media/'+p.name;(dist/name).parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(p,dist/name);allow.append(name)
    names=['hnb-media-overview-hr.html','hnb-media-overview-hr.pdf','hnb-media-brief-en.html','hnb-media-brief-en.pdf','hnb-media-brief-hr.html','hnb-media-brief-hr.pdf','hnb-media-slides-hr.html','hnb-media-slides-hr.pdf','media-publications.css','media-slides.js','media-citation.txt','media-reuse.txt','media-dictionary.html','media-methods-hr.html','media-methods-en.html','artifacts.json']
    names+=['hnb-reports.css']+[stem+ext for stem in ['hnb-u-medijskom-prostoru','hnb-od-rijeci-do-javnih-pitanja'] for ext in ['.pdf','.html','.webp']]
    names+=['SourceSans3-Regular.woff2','SourceSans3-Semibold.woff2','SourceSerif4Display-Regular.woff2','source-sans-LICENSE.txt','source-serif-LICENSE.txt']
    for name in names:
        p=site/'public/downloads'/name
        if not p.is_file():raise FileNotFoundError(p)
        shutil.copyfile(p,dist/'downloads'/name);allow.append('downloads/'+name)
    artifacts=json.loads((site/'public/downloads/artifacts.json').read_text(encoding='utf-8'))
    for lang,name in [('en','index.html'),('hr','hr.html')]:
        hr=lang=='hr';t=lambda en,hr_:hr_ if hr else en;n=lambda v,d=0:number(v,lang,d);c=content(data,lang)
        sections=[('hnb-pregled',t('Overview','Pregled')),('vidljivost',t('Visibility','Vidljivost')),('teme',t('Subjects','Teme')),('izvori',t('Sources','Izvori')),('istrazivanja',t('Research','Istraživanja')),('analiza',t('Methods & downloads','Metode i preuzimanja'))]
        nav=''.join(f'<a href="#{id}">{label}</a>' for id,label in sections)
        facts=''.join(f'<div class="fact"><strong>{a}</strong><span>{b}</span></div>' for a,b in [(n(s['hnb_publications']),t('publications with explicit HNB mentions','objava s izričitim spominjanjem HNB-a')),(n(s['outlets']),t('registered outlets represented','zastupljeni registrirani izvori')),(n(s['stable_sources']),t('sources observed in every full month','izvori opaženi u svakom punom mjesecu'))])
        findings=''.join(f'<article class="finding" id="{id}"><span class="claim-id">{id} · HNB_MEDIA</span><h3>{e(title)}</h3><p>{e(body)}</p><a href="data/media/findings.json">{t("Evidence record","Zapis o dokazu")} ↗</a></article>' for id,title,body in c['findings'])
        opts=''.join(f'<option value="{r["period"]}">{r["period"]}{" *" if r["coverage_state"]=="partial" else ""}</option>' for r in data['monthly'])
        sourceopts=f'<option value="all">{t("All eligible sources","Svi prihvatljivi izvori")}</option><option value="stable">{t("Observed in every full month","Opaženi u svakom punom mjesecu")}</option>'+''.join(f'<option value="{e(r["source_id"])}">{e(r["source_id"])}</option>' for r in [{'source_id':x} for x in data['selector_sources']])
        controls=f'<div class="controls" hidden data-media-js><label>{t("From","Od")}<select id="media-from">{opts}</select></label><label>{t("Through","Do")}<select id="media-to">{opts}</select></label><label>{t("Source population","Skup izvora")}<select id="media-source">{sourceopts}</select></label><label>{t("Measure","Mjera")}<select id="media-metric"><option value="count">{t("Publication count","Broj objava")}</option><option value="rate">{t("Per 10,000 eligible publications","Na 10.000 prihvatljivih objava")}</option></select></label><button id="media-reset">{t("Reset","Početni prikaz")}</button></div>'
        full=[r for r in data['monthly'] if r['period']<=s['last_full_period']]
        numeric=table([t('Month','Mjesec'),t('HNB count','Broj HNB'),t('HNB passing filter','HNB nakon filtra'),t('All passing filter','Sve nakon filtra'),t('Per 10,000','Na 10.000')],[(r['period'],n(r['hnb_count']),n(r['hnb_i']),n(r['background_i']),n(r['rate_per_10000'],2)) for r in full],'media-numeric-rows')
        subjects=''.join(f'<li><strong>{e(d["label_"+lang])}</strong><span class="amount">{n(s["subject_counts"][d["id"]])}</span> {t("publications matching words or phrases","objava s podudarnim riječima ili izrazima")}</li>' for d in data['subject_definitions'])
        sources=table([t('Outlet domain','Domena izvora'),t('Publications','Objave'),t('Share of sample','Udio u uzorku')],[(e(r['source_id']),n(r['hnb_count']),n(r['hnb_share']*100,2)+'%') for r in data['sources'][:25]],'media-source-rows')
        sensitivity=table([t('Definition / population','Definicija / skup'),t('Publications, full months','Objave, puni mjeseci')],[(e(k),n(v)) for k,v in c['sensitivity']])
        methods=''.join(f'<article><h3>{e(title)}</h3><p>{e(body)}</p></article>' for title,body in c['methods'])
        audit=list(csv.DictReader((site/'public/data/media/retrieval-audit.csv').open(encoding='utf-8')))
        role_labels={'editorial':('Eligible web publications','Prihvatljive web publikacije'),'hnb_own':('HNB own channels','Vlastiti kanali HNB-a'),'other_own':('Other identified own channels','Ostali prepoznati vlastiti kanali'),'audience':('Audience discussion','Rasprave publike'),'social_unresolved':('Unresolved social accounts','Nerazjašnjeni društveni računi'),'other_media_unresolved':('Other unresolved media','Ostali nerazjašnjeni mediji'),'unknown':('Unclassified web sources','Nerazvrstani web izvori')}
        totals={}
        for r in audit:totals[r['source_role']]=totals.get(r['source_role'],0)+int(r['explicit_publications'])
        audit_table=table([t('Source role','Uloga izvora'),t('Explicit-mention publications','Objave s izričitim spominjanjem')],[(t(*role_labels.get(k,(k,k))),n(v)) for k,v in totals.items()])
        methods+=f'<article><h3>{t("Source-role and text diagnostics","Dijagnostika uloga izvora i teksta")}</h3><p>{t("The table includes all available dates through 10 September 2026, including partial September. Only eligible editorial web publications enter the main series. The other rows describe retrieved candidates, not complete channel inventories.","Tablica obuhvaća sve dostupne datume do 10. rujna 2026., uključujući djelomičan rujan. Samo prihvatljive uredničke web publikacije ulaze u glavnu seriju. Ostali redci opisuju pronađene kandidate, a ne potpune popise kanala.")}</p>{audit_table}<p>{t("Full-month window: ","Razdoblje punih mjeseci: ")}{n(s["with_body"])} {t("publications with non-empty body text; ","objava s nepraznim tekstom; ")}{n(s["exact_body_groups"])} {t("different exact normalized raw-body hashes. These are not unique-story counts; near-copies and boilerplate limit exact matching.","različitih točnih normaliziranih otisaka izvornog teksta. To nije broj jedinstvenih priča; bliske kopije i ponavljajući sadržaj ograničavaju točno podudaranje.")}</p><a href="data/media/retrieval-audit.csv">{t("Retrieval audit · CSV","Provjera pronalaženja · CSV")}</a></article>'
        related=json.loads((site/'public/data/media/related-studies.json').read_text(encoding='utf-8'))
        related_html='<details><summary>'+t('Study and edition records','Zapisi studija i izdanja')+'</summary>'+''.join('<article><h3>'+e(r['title'])+'</h3><p>'+e('; '.join(r['authors']))+'</p><p>'+e(r['status_'+lang])+' · '+e(r['period'])+' · '+e(r['date_label_'+lang])+'</p><p>'+e(r['compatibility_'+lang])+'</p><p class="source-note">'+e(r['citation'])+'</p></article>' for r in related)+'</details>'
        downloads=[]
        for stem,label in [('hnb-media-overview-hr',t('Substantive overview · Croatian','Cjeloviti pregled · hrvatski')),('hnb-media-brief-'+lang,t('Executive brief · English','Sažetak za odlučivanje · hrvatski')),('hnb-media-slides-hr',t('Findings presentation · Croatian','Prezentacija nalaza · hrvatski'))]:
            a=next(a for a in artifacts if a['file']==stem+'.pdf');downloads.append(f'<li><b>{label}</b><div><a href="downloads/{stem}.html">HTML</a> · <a href="downloads/{stem}.pdf">PDF</a></div><small>{a["pages"]} {t("pages / slides","stranica / slajdova")} · {n(a["bytes"]/1024)} kB · 21. 9. 2026.</small></li>')
        for link,label in [('data/media/media-monthly.csv',t('Monthly aggregates · CSV','Mjesečni agregati · CSV')),('data/media/media-source-monthly.csv',t('Source × month · CSV','Izvor × mjesec · CSV')),('data/media/media-subjects.csv',t('Subject screens · CSV','Tematski skupovi · CSV')),('downloads/media-dictionary.html',t('Data dictionary','Rječnik podataka')),(f'downloads/media-methods-{lang}.html',t('Methods','Metode')),('data/media/source-registry.csv',t('Source registry','Registar izvora')),('downloads/hnb-media-rendering-source.zip',t('Offline rendering source package · ZIP','Izvorni paket za izvanmrežnu izgradnju · ZIP')),('release-manifest.json',t('Release manifest','Manifest izdanja')),('checksums.sha256','SHA-256'),('downloads/artifacts.json',t('Publication metadata','Metapodaci publikacija'))]:downloads.append(f'<li><a href="{link}">{label}</a></li>')
        specialist='studies/inflation/'+('hr.html' if hr else 'index.html')
        body=f'''<a class="skip" href="#main">{t('Skip to content','Preskoči na sadržaj')}</a><header><div class="wrap masthead"><a class="wordmark" href="{name}">HNB · {t('Media research','Medijska istraživanja')}</a><a class="language" id="media-language" lang="{'en' if hr else 'hr'}" href="{'index.html' if hr else 'hr.html'}">{'English' if hr else 'Hrvatski'}</a></div></header>
<div class="wrap hero"><p class="eyebrow">{t('Independent research · descriptive release','Neovisno istraživanje · opisno izdanje')}</p><h1>{e(c['title'])}</h1><p class="lead">{e(c['lead'])}</p><div class="actions"><a class="button" href="#vidljivost">{t('Explore the evidence','Istražite podatke')}</a><a class="button secondary" href="downloads/hnb-media-overview-hr.html">{t('Read the overview (Croatian)','Pročitajte cjeloviti pregled')}</a></div></div>
<div class="scope-strip"><div class="wrap"><p>{e(c['scope'])}</p></div></div><nav class="contents" aria-label="{t('Page contents','Sadržaj stranice')}"><div class="wrap">{nav}</div></nav>
<main id="main" class="wrap"><section class="section" id="hnb-pregled"><p class="eyebrow">01 · {t('Observed presence','Zabilježena prisutnost')}</p><h2>{t('A broad institutional view, within a defined archive','Širok institucionalni pregled unutar određenog arhiva')}</h2><p class="intro">{t('Explicit mentions across subjects show when and where the institution appears in this monitored web sample. Visibility here is not readership, trust or communication effectiveness.','Izričita spominjanja u različitim temama pokazuju kada se i gdje institucija pojavljuje u ovom praćenom internetskom uzorku. Vidljivost ovdje nije čitanost, povjerenje ni učinkovitost komunikacije.')}</p><div class="facts">{facts}</div><p class="source-note">{t('Headline window: 2021-01–2026-08. Exact register-domain eligibility; repeated captures merged.','Razdoblje glavnih vrijednosti: 2021-01–2026-08. Točno podudaranje domene s upisnikom; ponovljeni zapisi spojeni.')}</p><div class="finding-list">{findings}</div></section>
<section class="section" id="vidljivost"><p class="eyebrow">02 · {t('Time and denominator','Vrijeme i nazivnik')}</p><h2>{t('When do captured HNB mentions appear?','Kada se pojavljuju zabilježena spominjanja HNB-a?')}</h2><p class="intro">{t('Inspect counts or the rate per 10,000 query-eligible archive publications. The dashed line marks the January 2024 collection change, not a policy effect.','Pregledajte broj objava ili stopu na 10.000 arhivskih objava koje prolaze isti filtar. Isprekidana crta označava promjenu prikupljanja u siječnju 2024., a ne učinak politike.')}</p>{controls}<p class="view-status" id="media-view-status">2021-01–2026-08 · {n(s['hnb_publications'])} {t('observed publications','opaženih objava')}</p><p id="media-empty" class="empty-state" hidden></p><figure class="figure"><h3 id="media-chart-label">{t('Publications containing explicit HNB mentions','Objave s izričitim spominjanjem HNB-a')}</h3><div id="media-chart">{chart(full,lang)}</div><figcaption id="media-selected-note">{e(c['methods'][4][1])}</figcaption></figure><div class="actions" hidden data-media-js><button id="media-export-csv">CSV</button><button id="media-export-svg">SVG</button><button id="media-copy">{t('Copy view link','Kopiraj poveznicu prikaza')}</button><button id="media-definition-open">{t('Definitions','Definicije')}</button></div><label class="sr-only" for="media-copy-fallback">{t('Link to copy','Poveznica za kopiranje')}</label><input id="media-copy-fallback" hidden readonly><details><summary>{t('Numeric alternative and matched denominators','Brojčani prikaz i usklađeni nazivnici')}</summary>{numeric}<p class="source-note">{t('A dash means unavailable, not zero. An asterisk marks a partial month.','Crtica označava nedostupnu vrijednost, a ne nulu. Zvjezdica označava djelomičan mjesec.')}</p></details><noscript><p class="note">{t('The complete default chart and table are available without JavaScript. Use aggregate downloads for other views.','Cijeli početni grafikon i tablica dostupni su bez JavaScripta. Za druge prikaze koristite preuzimanje agregata.')}</p></noscript></section>
<section class="section" id="teme"><p class="eyebrow">03 · {t('Exploratory subject screens','Istraživački pregled tema')}</p><h2>{t('Which subjects are present in the captured text?','Koje su teme prisutne u zabilježenom tekstu?')}</h2><p class="intro">{e(c['findings'][3][2])}</p><ul class="subject-list">{subjects}</ul><p class="note">{e(c['sections'][4][1][2])}</p><p class="source-note">2021-01–2026-08 · {t('Title and body; overlapping assignments; no independent validation.','Naslov i tekst; preklapajuće oznake; bez neovisne validacije.')} <a href="data/media/subject-definitions.json">{t('Exact definitions','Točne definicije')}</a></p></section>
<section class="section" id="izvori"><p class="eyebrow">04 · {t('Source composition','Sastav izvora')}</p><h2>{t('Where does the observed coverage appear?','Gdje se pojavljuju opažene objave?')}</h2><p class="intro">{e(c['findings'][1][2])}</p><label hidden data-media-js>{t('Order sources','Poredaj izvore')} <select id="media-sort"><option value="count">{t('By count','Prema broju')}</option><option value="name">{t('Alphabetically','Abecedno')}</option></select></label><p id="media-source-scope" class="source-note">2021-01–2026-08 · {t('all eligible sources; first 25 shown','svi prihvatljivi izvori; prikazano prvih 25')}</p>{sources}<p class="source-note">{t('The table follows the selected dates and compares all eligible sources. It does not inherit the chart’s single-source selection.','Tablica prati odabrane datume i uspoređuje sve prihvatljive izvore. Ne preuzima odabir pojedinačnog izvora iz grafikona.')} <a href="data/media/media-sources.csv">{t('Complete ranking · CSV','Cijeli poredak · CSV')}</a></p><details><summary>{t('Sensitivity to retrieval and source scope','Osjetljivost na pronalaženje i skup izvora')}</summary>{sensitivity}<p>{e(c['sections'][5][1][1])}</p></details></section>
<section class="section" id="istrazivanja"><p class="eyebrow">05 · {t('Connected research','Povezana istraživanja')}</p><h2>{t('Go deeper into the inflation debate','Detaljnije o raspravi o inflaciji')}</h2><article class="study-card"><p class="eyebrow">{t('Specialist study · separate corpus','Specijalistička studija · zaseban korpus')}</p><h3>{t('HNB in the inflation debate','HNB u raspravi o inflaciji')}</h3><p>{e(c['sections'][6][1][0])}</p><p class="source-note">Petra Palić · Luka Sikić · 17. 9. 2026.<br><i>Pasivno zamijenjena: cijena inflacije koju ne mjeri indeks potrošačkih cijena</i></p><a class="button" href="{specialist}">{t('Open the specialist study','Otvori specijalističku studiju')}</a></article><p class="note">{e(c['sections'][6][1][1])}</p><h3>{t('What needs new evidence?','Za što su potrebni novi dokazi?')}</h3><p>{e(c['sections'][7][1][0])}</p><p class="source-note">{t('Governor visibility has a separate unreviewed draft; official-message uptake remains a proposal. Neither supplies verified findings here. The older inflation edition is historical, not independent replication.','O vidljivosti guvernera postoji zaseban nacrt koji još nije provjeren za ovo izdanje; preuzimanje službenih poruka ostaje prijedlog. Starije inflacijsko izdanje povijesni je materijal, a ne neovisna replikacija.')}</p></section>
<section class="section" id="analiza"><p class="eyebrow">06 · {t('Methods and release','Metode i izdanje')}</p><h2>{t('Read the limits alongside the numbers','Čitajte ograničenja uz brojke')}</h2><div class="methods-grid">{methods}</div><p class="source-note">{t('Eligibility reference','Izvor za prihvatljivost')}: <a href="https://aem.hr/elektronicke-publikacije/">{t('Agency for Electronic Media register','Upisnik Agencije za elektroničke medije')}</a> · 21. 9. 2026. · <a href="data/media/analysis-manifest.json">{t('Analysis lineage','Analitičko podrijetlo')}</a></p><h3>{t('Publications and reproducible inputs','Publikacije i ulazni podaci za ponovljivost')}</h3><ul class="download-list">{''.join(downloads)}</ul><p>{e(c['sections'][7][1][1])}</p><p><a href="downloads/media-citation.txt">{t('Citation','Citiranje')}</a> · <a href="downloads/media-reuse.txt">{t('Reuse and data restrictions','Ponovna uporaba i ograničenja podataka')}</a></p></section></main>
<footer class="footer"><div class="wrap">{t('Independent research resource; no HNB affiliation or endorsement is implied.','Neovisni istraživački izvor; ne podrazumijeva pripadnost HNB-u ni njegovo odobrenje.')}<br>HNB_MEDIA · {t('data','podaci')} {release['data_version']} · {t('method','metoda')} {release['method_version']} · {t('presentation','prikaz')} {data['presentation_version']} · {t('author review pending','autorska provjera u tijeku')}</div></footer>
<dialog id="media-definition" aria-labelledby="media-definition-title"><h2 id="media-definition-title">{t('Count, rate and coverage','Broj, stopa i obuhvat')}</h2><p>{e(c['methods'][3][1])}</p><p>{e(c['methods'][4][1])}</p><button id="media-definition-close">{t('Close','Zatvori')}</button></dialog><p class="sr-only" id="media-announcement" aria-live="polite"></p><script id="media-data" type="application/json">{json.dumps(data,ensure_ascii=False,separators=(',',':'),allow_nan=False).replace('<',chr(92)+'u003c')}</script><script src="media.js" defer></script>'''
        body=body.replace('<section class="section" id="analiza">',report_cards(artifacts,lang)+related_html+'<section class="section" id="analiza">')
        body=body.replace('<a href="#analiza">', '<a href="#izvjestaj">'+t('Reports','Izvještaji')+'</a><a href="#analiza">',1)
        body=body.replace('href="downloads/hnb-media-overview-hr.html">'+t('Read the overview (Croatian)','Pročitajte cjeloviti pregled'), 'href="#izvjestaj">'+t('Read the two reports (Croatian)','Pročitajte dva izvještaja'),1)
        template=(site/'src'/name).read_text(encoding='utf-8')
        for k,v in {'LANG':lang,'TITLE':e(c['title']),'DESCRIPTION':e(c['lead']),'BODY':body}.items():template=template.replace('@@'+k+'@@',v)
        base=(os.environ.get('SITE_URL') or json.loads((site/'content/releases.json').read_text(encoding='utf-8'))['canonical_url'] or '').rstrip('/')
        if base:template=template.replace('</head>',f'<link rel="canonical" href="{e(base)}/{"" if name=="index.html" else name}"></head>')
        assert '@@' not in template
        (dist/name).write_text(template,encoding='utf-8');allow.append(name)
    return allow
