"""Specialist manuscript card for the local preview."""


def specialist_study(lang):
    t = lambda hr, en: hr if lang == 'hr' else en
    return f'''<section class="specialist-section" id="specijalisticka-studija" aria-labelledby="specialist-heading"><span id="istrazivanja"></span><div class="wrap specialist-layout">
<div class="specialist-copy"><p class="eyebrow">{t('Specijalistička studija · zaseban korpus','Specialist study · separate corpus')}</p><h2 id="specialist-heading">{t('HNB u raspravi o inflaciji','HNB in the inflation debate')}</h2>
<p>{t('Ažurirana inflacijska studija Petre Palić i Luke Sikića (28. rujna 2026.) ponovno analizira ponderiranu institucionalnu vidljivost kroz 68 potpunih mjeseci od siječnja 2021. do kolovoza 2026. Primarni tjedni model povezuje inflaciju višu za jedan postotni bod s ponderiranim udjelom nižim za 0,25 postotnih bodova (95%-tni interval: 0,11–0,39; 295 tjedana u procjeni).', 'The updated inflation study by Petra Palić and Luka Sikić (28 September 2026) reanalyses weighted institutional visibility over 68 complete months, from January 2021 to August 2026. The primary weekly model associates inflation one percentage point higher with a weighted share 0.25 percentage points lower (95% interval: 0.11–0.39; 295 weeks in the estimation).')}</p>
<p>{t('Godišnje kontrole i specifikacija obujma ograničavaju zaključak. Stabilna veza s budućim očekivanjima potrošača nije utvrđena. Rad donosi nove procjene modela, provjere osjetljivosti i grafikone.', 'Year controls and the volume specification qualify the conclusion. No stable link with future consumer expectations was established. The paper presents new model estimates, sensitivity checks and figures.')}</p></div>
<article class="study-card"><p class="eyebrow">{t('Hrvatski rukopis','Croatian manuscript')}</p><p class="manuscript-authors">Petra Palić · Luka Sikić</p><p class="manuscript-date"><time datetime="2026-09-28">28. 9. 2026.</time></p><h3 id="manuscript-heading" lang="hr"><em>Pasivno zamijenjena: cijena inflacije koju ne mjeri indeks potrošačkih cijena</em></h3><p class="small">{t('18 stranica · hrvatski rukopis','18 pages · Croatian manuscript')}<br>{t('68 potpunih mjeseci · 295 tjedana u procjeni','68 complete months · 295 fitted weeks')}</p><div class="report-actions"><a class="button" href="downloads/PAPER_EXT.pdf" download>PDF ↓</a><a href="downloads/PAPER_EXT.html" download hreflang="hr">HTML ↓</a><a href="downloads/PAPER_EXT.html" hreflang="hr">{t('Čitajte online','Read online')} ↗</a></div></article>
</div></section>'''
