"""Bilingual reading, inspection and comparison components."""
from html import escape as esc
from charts import chart

def explorer(lang,e,i):
    hr=lang=='hr';t=lambda en,cr:cr if hr else en
    last=e['observations'][-1];d=i['observations'][-1]['primary'];root='grafikon' if hr else 'overview'
    option=lambda value,label,selected=False:f'<option value="{value}"{" selected" if selected else ""}>{label}</option>'
    options=''.join(option(r['period'],r['period'],r==last) for r in e['observations'])
    rows=''.join(f'<tr><th scope="row">{r["period"]}</th><td>{100*(e["baseline"]["monthly"]-r["gap"]):.2f}</td><td>{100*r["gap"]:.2f}</td><td>{r["inflation"]:.1f}</td></tr>' for r in e['observations'])
    lenses=[('visibility','Is visibility changing?','Mijenja li se vidljivost?'),('composition','How much depends on the sources?','Koliko rezultat ovisi o izvorima?'),('inflation','How does visibility relate to inflation?','Kako je vidljivost povezana s inflacijom?'),('understanding','What about public understanding?','Što znamo o razumijevanju javnosti?')]
    buttons=''.join(f'<button type="button" data-lens="{key}" aria-pressed="false">{t(en,cr)}</button>' for key,en,cr in lenses)
    return f'''
<section class="signature" id="{root}" aria-labelledby="overview-title"><div class="wrap">
<div class="section-heading"><div><p class="eyebrow">01 / {t('Explore the evidence','Istražite dokaze')}</p><h2 id="overview-title">{t('Start with a question.<br>Follow it into the evidence.','Počnite pitanjem.<br>Pratite ga do dokaza.')}</h2></div><div class="chart-guide"><span class="line-key"></span>{t('Selected measure','Odabrani pokazatelj')}<br><span class="line-key orange"></span>HICP {t('inflation','inflacija')}<small>{t('Separate scales, aligned months','Zasebne skale, poravnati mjeseci')}</small></div></div>
<p class="chart-intro">{t('Weighted visibility relates institutional prominence and potential reach to the inflation corpus. It is not readership. Generic central-bank references can also identify the ECB or other institutions.','Ponderirana vidljivost povezuje institucionalnu istaknutost i potencijalni doseg s inflacijskim korpusom. Nije mjera čitanosti. Generičke reference mogu obuhvatiti ESB ili druge središnje banke.')}</p>
<div class="question-lenses" aria-label="{t('Questions','Pitanja')}" hidden data-js>{buttons}</div>
<p id="lens-interpretation" hidden data-js class="lens-interpretation" aria-live="polite">{t('Choose a question to configure the view, or use the controls below.','Odaberite pitanje za prilagodbu prikaza ili koristite kontrole u nastavku.')}</p>
<div class="chart-toolbar" hidden data-js><div class="chart-selectors">
<label for="window">{t('Period','Razdoblje')}<select id="window">{option('all',t('Full history · Jan 2021–May 2026','Cijelo razdoblje · sij. 2021. – svi. 2026.'),True)}{option('new',t('Recent period · Apr 2024–May 2026','Kasnije razdoblje · tra. 2024. – svi. 2026.'))}</select></label>
<label for="metric">{t('Measure','Pokazatelj')}<select id="metric">{option('share',t('Weighted share · higher = more visible','Ponderirani udio · više = veća vidljivost'))}{option('gap',t('Attention gap · higher = less visible','Jaz u pažnji · više = manja vidljivost'))}{option('article',t('Article share · %','Udio objava · %'))}{option('centrality',t('Network centrality · index','Mrežna centralnost · indeks'))}{option('hhi',t('Concentration of weight · HHI','Koncentracija pondera · HHI'))}</select></label>
<label for="sample">{t('Series definition','Definicija serije')}<select id="sample">{option('primary',t('Primary corpus','Primarni korpus'))}{option('common',t('Common sources · 258 source labels','Zajednički izvori · 258 oznaka'))}</select></label>
</div></div><p id="chart-scope" class="chart-scope">{t('Full-history weighted share: 0–18%.','Ponderirani udio za cijelo razdoblje: 0–18%.')}</p>
<figure class="timeline"><div class="chart-panel"><div class="chart-title"><h3 id="visibility-title">{t('Weighted institutional visibility','Ponderirana institucionalna vidljivost')}</h3><span id="visibility-unit">{t('Weighted share (%) · higher means more visible','Ponderirani udio (%) · više znači veću vidljivost')}</span></div><div id="gap-chart" class="chart" role="img" aria-label="{t('Monthly weighted visibility','Mjesečna ponderirana vidljivost')}">{chart(e['observations'],'share',baseline=e['baseline']['monthly'])}</div></div>
<div class="chart-panel"><div class="chart-title"><h3>{t('Inflation in Croatia','Inflacija u Hrvatskoj')}</h3><span>HICP · {t('year-on-year','godišnja stopa')}, %</span></div><div id="inflation-chart" class="chart" role="img" aria-label="{t('HICP inflation, aligned to the same months','HICP inflacija za iste mjesece')}">{chart(e['observations'],'inflation')}</div></div>
<figcaption>{t('HICP compares prices with the same month a year earlier. Potential reach is not observed audience exposure. The primary and common-source series each use their own numerator, denominator and historical reference.','HICP uspoređuje cijene s istim mjesecom prethodne godine. Potencijalni doseg nije opažena izloženost publike. Primarna serija i serija zajedničkih izvora koriste vlastiti brojnik, nazivnik i povijesnu referencu.')}</figcaption></figure>
<div class="period-inspector" hidden data-js><label for="period">{t('Inspect a month','Odaberite mjesec')}<select id="period">{options}</select></label><output id="period-values" aria-live="polite">{last['period']} · {d['share']:.2f}%</output></div>
<div class="reading-strip" hidden data-js aria-label="{t('Level, direction and evidence','Razina, smjer i dokazi')}"><article><p class="eyebrow">{t('Level / selected month','Razina / odabrani mjesec')}</p><strong id="state-level">{d['share']:.2f}%</strong><p id="level-context">{last['period']}</p></article><article><p class="eyebrow">{t('Direction / endpoints','Smjer / krajnje točke')}</p><strong id="state-direction">{t('Compare two months','Usporedite dva mjeseca')}</strong><p id="direction-context"></p></article><article><p class="eyebrow">{t('Evidence / selected finding','Dokazi / odabrani nalaz')}</p><strong id="state-evidence">{t('Sensitive to time controls','Osjetljivo na vremenske kontrole')}</strong><p id="evidence-context"></p><a href="#analysis-desk">{t('See the checks and criteria ↓','Provjere i kriteriji ↓')}</a></article></div>
<div class="view-actions" hidden data-js><button type="button" id="inspect-current">{t('Inspect this measure','Pojedinosti pokazatelja')}</button><button type="button" data-open-compare>{t('Compare results','Usporedite rezultate')}</button><button type="button" id="reset-view">{t('Reset selections','Početne postavke')}</button><button type="button" data-copy="{root}">{t('Copy chart link','Kopiraj poveznicu grafikona')}</button><button type="button" id="export-svg">{t('Selected chart · SVG ↓','Odabrani grafikon · SVG ↓')}</button><button type="button" id="export-csv">{t('Selected period · CSV ↓','Odabrano razdoblje · CSV ↓')}</button></div><p id="action-status" class="action-status" role="status"></p>
<div class="point-evidence"><p id="period-context">{t('Saved monthly aggregates · manuscript 17 September 2026.','Spremljeni mjesečni agregati · rukopis od 17. rujna 2026.')}</p><p id="observation-note"></p><a href="#media-context">{t('Media context and source diagnostics','Medijski kontekst i izvori')}</a> · <a href="data/inspection.json" download>{t('Inspection data · JSON ↓','Podatci za pregled · JSON ↓')}</a></div>
<div class="download-row"><a href="figures/visibility-later{'-hr' if hr else ''}.png" download>{t('Fixed recent-period primary share figure ↓','Primarni udio za kasnije razdoblje ↓')}</a><a href="figures/attention-gap.png" download>{t('Full-history primary gap figure ↓','Primarni jaz za cijelo razdoblje ↓')}</a><a href="data/monthly-series.csv" download>{t('Full-sample primary data · CSV ↓','Primarni podatci za cijeli uzorak · CSV ↓')}</a></div>
<details class="data-details"><summary>{t('Monthly values as a table','Mjesečne vrijednosti u tablici')}</summary><div class="table-scroll" tabindex="0"><table><caption id="monthly-caption">{t('Primary corpus: share %, gap pp, inflation %.','Primarni korpus: udio %, jaz pb, inflacija %.')}</caption><thead id="monthly-head"><tr><th scope="col">{t('Month','Mjesec')}</th><th scope="col">{t('Share (%)','Udio (%)')}</th><th scope="col">{t('Gap (pp)','Jaz (pb)')}</th><th scope="col">HICP (%)</th></tr></thead><tbody id="monthly-body">{rows}</tbody></table></div></details>
</div></section>
<section class="wrap section inspection-desk" id="analysis-desk" aria-labelledby="desk-title"><div class="section-heading"><div><p class="eyebrow">{t('Inspect / compare','Pregled / usporedba')}</p><h2 id="desk-title">{t('What is moving?<br>What supports the conclusion?','Što se mijenja?<br>Na čemu počiva zaključak?')}</h2></div><p class="desk-context" id="desk-context"></p></div>
<div class="mode-actions" hidden data-js><button type="button" data-mode="read" aria-pressed="true">{t('Read','Čitanje')}</button><button type="button" data-mode="inspect" aria-pressed="false">{t('Inspect measure','Pregled pokazatelja')}</button><button type="button" data-mode="compare" aria-pressed="false">{t('Compare','Usporedba')}</button></div>
<noscript><p><a href="data/inspection.json" download>{t("Saved comparisons and supporting values · JSON ↓","Spremljene usporedbe i potporne vrijednosti · JSON ↓")}</a></p></noscript><details id="comparison" hidden data-js><summary>{t('Open the comparison desk','Otvori usporedbe')}</summary>
<div class="endpoint-comparison"><h3>{t('Two observations, one stated definition','Dva opažanja, jedna navedena definicija')}</h3><div class="controls"><label for="compare-from">{t('From','Od')}<select id="compare-from"></select></label><label for="compare-to">{t('To','Do')}<select id="compare-to"></select></label></div><div id="endpoint-result" aria-live="polite"></div><p id="comparison-basis"></p><p class="caveat">{t('An endpoint difference is descriptive. It is not a fitted trend, a significance test or a policy-performance score. Changing the series definition recalculates both endpoints.','Razlika krajnjih točaka opisni je podatak. Nije procijenjeni trend, test značajnosti ni ocjena politike. Promjena definicije serije ponovno izračunava obje točke.')}</p><button type="button" id="toggle-sample">{t('Compare common sources','Usporedi zajedničke izvore')}</button></div>
<div class="robustness-desk"><h3>{t('The same question, alternative specifications','Isto pitanje, alternativne specifikacije')}</h3><div class="controls"><label for="compare-finding">{t('Finding','Nalaz')}<select id="compare-finding"><option value="F1">F1 · {t('Inflation association','Povezanost s inflacijom')}</option><option value="F2">F2 · {t('Visibility trend','Trend vidljivosti')}</option><option value="F3">F3 · {t('Expectations','Očekivanja')}</option><option value="F4">F4 · {t('Network position','Mrežni položaj')}</option></select></label><label>{t('Model frequency','Frekvencija modela')}<select data-bind="frequency"><option value="weekly">{t('Weekly','Tjedno')}</option><option value="monthly">{t('Monthly','Mjesečno')}</option></select></label></div><p id="robustness-intro"></p><div id="robustness-chart" role="img"></div><div class="table-scroll" tabindex="0"><table id="robustness-table"></table></div><p id="robustness-conclusion" class="interval-meaning" aria-live="polite"></p><details class="evidence-rules"><summary>{t('How the evidence labels are defined','Kako se određuju oznake dokaza')}</summary><p>{t('“Sensitive to time controls”: a displayed time-control interval includes zero. “Same direction across source definitions”: primary and common-source trend estimates point the same way; interval precision is reported separately. “Depends on survey assignment”: the reported future horizons differ across assignments. “Direction uncertain”: the reference centrality interval includes zero. These labels summarise the named checks; they are not confidence grades. Related models are not independent votes.','„Osjetljivo na vremenske kontrole”: prikazani interval uz vremenske kontrole obuhvaća nulu. „Isti smjer u različitim definicijama izvora”: primarni trend i trend zajedničkih izvora imaju isti smjer, a preciznost intervala prikazuje se zasebno. „Ovisi o pridruživanju ankete”: značajni budući horizonti razlikuju se. „Neizvjestan smjer”: referentni interval centralnosti obuhvaća nulu. Oznake sažimaju navedene provjere i nisu ocjene pouzdanosti. Povezani modeli nisu neovisni glasovi.')}</p></details><div class="actions"><a href="#finding-records">{t('Trace this finding ↓','Pratite podrijetlo nalaza ↓')}</a><button type="button" id="export-comparison">{t('Export this comparison · CSV ↓','Preuzmi usporedbu · CSV ↓')}</button><button type="button" data-copy="analysis-desk">{t('Copy comparison link','Kopiraj poveznicu usporedbe')}</button></div></div>
</details></section>
<dialog id="indicator-dialog" aria-labelledby="indicator-title"><div class="dialog-header"><p class="eyebrow">{t('Inspect a measure','Pregled pokazatelja')}</p><button type="button" id="close-indicator">{t('Return to chart ×','Natrag na grafikon ×')}</button></div><p id="indicator-context" class="dialog-context"></p><label for="indicator-choice">{t('Indicator','Pokazatelj')}</label><select id="indicator-choice"></select><h2 id="indicator-title"></h2><p id="indicator-value" class="indicator-value"></p><dl id="indicator-details"></dl><div class="dialog-actions"><button type="button" id="indicator-evidence">{t('See associated finding','Pogledaj povezani nalaz')}</button><button type="button" id="copy-indicator">{t('Copy inspection link','Kopiraj poveznicu pregleda')}</button><a href="{'index.html' if hr else 'hr.html'}">{'English' if hr else 'Hrvatski'} ↗</a></div><p id="dialog-status" role="status"></p></dialog>
<div id="copy-fallback-area" class="wrap"><label class="sr-only" for="copy-fallback">{t('Text to copy','Tekst za kopiranje')}</label><textarea id="copy-fallback" aria-label="{t('Text to copy','Tekst za kopiranje')}" readonly hidden></textarea><p id="global-status" class="action-status" role="status"></p></div>
'''

def media_context(lang,e,i):
    t=lambda en,cr:cr if lang=='hr' else en
    channel_names={'web':('Web','Web'),'comment':('Comments','Komentari'),'forum':('Forums','Forumi'),'twitter':('X / Twitter','X / Twitter')}
    channels=', '.join(t(*channel_names.get(x['channel'],(x['channel'].title(),x['channel'].title()))) for x in sorted(i['channels'],key=lambda x:-x['items']))
    return f'''<section class="media-context" id="media-context"><div class="wrap section"><p class="eyebrow">{t('Media environment / study scope','Medijsko okruženje / obuhvat')}</p><h2>{t('A media corpus is not an audience.','Medijski korpus nije publika.')}</h2><div class="scope-grid"><article><h3>{t('What the study observes','Što istraživanje opaža')}</h3><p>{t('Recorded institutional items across these channel labels','Zabilježene institucionalne objave u ovim kanalima')}: {channels}. {t('Web items dominate this corpus. The visibility numerator uses inflation-relevant institutional items; its denominator uses the monitored inflation corpus. Dates: January 2021–May 2026.','Web objave prevladavaju u korpusu. Brojnik vidljivosti koristi institucionalne objave relevantne za inflaciju, a nazivnik praćeni inflacijski korpus. Razdoblje: siječanj 2021. – svibanj 2026.')}</p><p>{t('A publisher’s website is an online source even when its brand also operates television or print. This corpus measures publication instances rather than population-wide news consumption.','Web stranica nakladnika internetski je izvor i kada isti brend djeluje na televiziji ili u tisku. Korpus mjeri pojedinačne objave, a ne potrošnju vijesti cjelokupnog stanovništva.')}</p></article><article><h3>{t('Four different concepts','Četiri različita pojma')}</h3><dl class="concept-definitions"><dt>{t('Potential reach','Potencijalni doseg')}</dt><dd>{t('Estimated opportunity to encounter an item.','Procijenjena mogućnost susreta s objavom.')}</dd><dt>{t('Exposure','Izloženost')}</dt><dd>{t('Evidence that a person actually encountered it.','Dokaz da je osoba doista susrela objavu.')}</dd><dt>{t('Attention','Pozornost')}</dt><dd>{t('Evidence of engagement with the message.','Dokaz bavljenja sadržajem poruke.')}</dd><dt>{t('Understanding','Razumijevanje')}</dt><dd>{t('Evidence of what a person understood.','Dokaz o tome što je osoba razumjela.')}</dd></dl><p>{t('Reach summed across items is an additive weight, not a count of unique people. Audiences and repeated stories can overlap.','Zbroj dosega objava aditivni je ponder, a ne broj jedinstvenih osoba. Publike i preneseni tekstovi mogu se preklapati.')}</p></article></div>
<aside class="external-context"><p class="eyebrow">{t('External context / 2025 only','Vanjski kontekst / samo 2025.')}</p><p>{t('The Reuters Institute’s 2025 Croatia profile describes a market combining commercial television, public-service broadcasting and online news. Its audience research uses self-reported survey answers: YouGov, online questionnaire, mid-January to late February 2025, demographic quotas and weighting. Interpret it as context for the online population in 2025, not as measured exposure to this study’s items throughout 2021–2026.','Profil Hrvatske Reutersova instituta iz 2025. opisuje tržište komercijalne televizije, javnog servisa i internetskih vijesti. Istraživanje publike temelji se na anketnim iskazima: YouGov, internetski upitnik, sredina siječnja – kraj veljače 2025., demografske kvote i ponderiranje. To je kontekst internetske populacije u 2025., a ne mjerenje izloženosti objavama ovog istraživanja tijekom 2021. – 2026.')} <a href="https://reutersinstitute.politics.ox.ac.uk/digital-news-report/2025/croatia">{t('Croatia profile','Profil Hrvatske')}</a> · <a href="https://reutersinstitute.politics.ox.ac.uk/digital-news-report/2025/methodology">{t('Survey methodology','Metodologija ankete')}</a>.</p></aside>
<div class="concentration-desk" hidden data-js><div class="section-heading"><div><p class="eyebrow">{t('Selected-month diagnostics','Dijagnostika odabranog mjeseca')}</p><h3>{t('How much weight sits with a few contributions?','Koliki dio pondera nose najveći doprinosi?')}</h3></div><p id="diagnostic-context"></p></div><div class="diagnostic-grid" id="diagnostic-values"></div><p id="diagnostic-definition"></p><details><summary>{t('Inspect domain contributions','Pregledajte doprinose domena')}</summary><p>{t('Domain labels are shown alphabetically by default. A domain, news brand and ownership group are different units. The shares below describe contributions to the institutional numerator, not quality, independence or audience market share.','Oznake domena početno su poredane abecedno. Domena, medijski brend i vlasnička grupa različite su jedinice. Udjeli opisuju doprinos institucionalnom brojniku, a ne kvalitetu, neovisnost ili tržišni udio publike.')}</p><label for="source-sort">{t('Order','Poredak')}<select id="source-sort"><option value="name">{t('Domain · alphabetical','Domena · abecedno')}</option><option value="items">{t('Relevant item count','Broj relevantnih objava')}</option><option value="weight">{t('Contribution to institutional weight','Doprinos institucionalnom ponderu')}</option></select></label><div class="table-scroll" tabindex="0"><table id="source-table"></table></div><p id="domain-scope"></p><button type="button" id="export-sources">{t('Domain contributions · CSV ↓','Doprinosi domena · CSV ↓')}</button></details><p class="caveat">{t('The five-source and ten-item shares use all contributing source labels and items. The table lists domain-form labels with relevant items. Publication instances are not deduplicated story counts; repeated distribution does not by itself demonstrate independent editorial attention.','Udjeli pet izvora i deset objava koriste sve oznake izvora i objave koje doprinose. Tablica prikazuje oznake u obliku domena s relevantnim objavama. Pojedinačne objave nisu broj jedinstvenih priča; ponovljena distribucija sama po sebi ne dokazuje neovisnu uredničku pozornost.')}</p></div></div></section>'''

def finding_records(lang,e,i):
    t=lambda en,cr:cr if lang=='hr' else en
    html=f'<section class="wrap section finding-records" id="finding-records"><p class="eyebrow">{t("Traceable findings / edition 2026-09-17","Sljedivi nalazi / izdanje 2026-09-17")}</p><h2>{t("A finding you can trace and cite.","Nalaz koji možete provjeriti i citirati.")}</h2><p>{t("Each identifier refers to a fixed research finding. The controls above change the view; they do not rewrite its reference model.","Svaka oznaka upućuje na određeni istraživački nalaz. Kontrole mijenjaju prikaz, a ne referentni model nalaza.")}</p>'
    for r in i['findings']:
        html+=f'''<details id="record-{r['id']}"><summary><span class="record-id">{r['id']}</span> {t(r['finding'],r['finding_hr'])}</summary><dl><dt>{t('Reference model','Referentni model')}</dt><dd>{esc(t(r['model'],r['model_hr']))}</dd><dt>{t('Measure and sample','Pokazatelj i uzorak')}</dt><dd>{esc(t(r['measure'],r['measure_hr']))} · {esc(t(r['sample'],r['sample_hr']))}</dd><dt>{t('Manuscript location','Mjesto u rukopisu')}</dt><dd>{esc(t(r['reference'],r['reference_hr']))}</dd><dt>{t('Versions','Verzije')}</dt><dd>{t('Data','Podatci')}: {r['data_version']} · {t('Method','Metoda')}: {r['method_version']} · {t('Presentation','Prezentacija')}: {r['presentation_version']}</dd><dt>{t('Verification','Provjera')}</dt><dd>{t('Matched to saved outputs. Author review pending.','Uspoređeno sa spremljenim rezultatima. Čeka autorsku provjeru.')}</dd></dl><p class="record-citation">Palić &amp; Sikić (2026), {r['id']}: {t(r['finding'],r['finding_hr'])} {t('Extended manuscript, 17 September 2026.','Prošireni rukopis, 17. rujna 2026.')}</p><div class="actions"><button type="button" hidden data-js data-record-compare="{r['id']}">{t('Inspect supporting comparisons','Pregledaj potporne usporedbe')}</button><button type="button" hidden data-js data-cite="{r['id']}">{t('Copy citation','Kopiraj citat')}</button><button type="button" hidden data-js data-copy="record-{r['id']}">{t('Copy record link','Kopiraj poveznicu nalaza')}</button></div></details>'''
    html+=f'''<p><a href="data/findings.json" download>{t('Finding records and revision history · JSON ↓','Zapisi nalaza i povijest izmjena · JSON ↓')}</a> · <a href="data/inspection.json" download>{t('Supporting values and comparisons · JSON ↓','Potporne vrijednosti i usporedbe · JSON ↓')}</a></p><div class="revision-ledger"><h3>{t('What changed in this release?','Što je promijenjeno u ovom izdanju?')}</h3><p><b>2026-09-19.2 · {t('Editorial and evidence presentation','Urednička dorada i prikaz dokaza')}.</b> {t('Added context-preserving inspection, comparison controls, source concentration summaries from existing scored records and fixed finding records. The published research estimates and their methods are unchanged.','Dodani su pregled uz očuvanje konteksta, usporedbe, sažetci koncentracije iz postojećih bodovanih zapisa i stalne oznake nalaza. Objavljene istraživačke procjene i metode nisu promijenjene.')}</p><details><summary>{t('How future revisions are labelled','Kako se označavaju buduće izmjene')}</summary><dl><dt>{t('Data correction','Ispravak podataka')}</dt><dd>{t('Identifies corrected observations and any effect on the conclusion.','Navodi ispravljena opažanja i učinak na zaključak.')}</dd><dt>{t('Method change','Promjena metode')}</dt><dd>{t('Identifies changed calculations and the scope of valid comparisons.','Navodi promjene izračuna i obuhvat valjanih usporedbi.')}</dd><dt>{t('Editorial clarification','Uredničko pojašnjenje')}</dt><dd>{t('Changes explanation or presentation while preserving the research estimates.','Mijenja objašnjenje ili prikaz uz očuvanje istraživačkih procjena.')}</dd></dl></details></div></section>'''
    return html
